export const ReportConfig = {
    incomeAndFoodSourceResponses: [
        { label: 'Livestock Production (including meat, milk, hides, skins, and by products/manure, pasture)', key: 'livestockProduction' },
        { label: 'Poultry Production including meat and egg production', key: 'poultryProduction' },
        { label: 'Pasture/Fodder crop production', key: 'pastureFodderProduction' },
        { label: 'Cash crop production', key: 'cashCropProduction' },
        { label: 'Food production', key: 'foodCropProduction' },
        { label: 'Casual wedge labor', key: 'casualOrWagedLabour' },
        { label: 'Formal wedge labor', key: 'formalWagedLabour' },
        { label: 'Fishing', key: 'fishing' },
        { label: 'Hunting and gathering', key: 'huntingAndGathering' },
        { label: 'Small Business', key: 'smallBusiness' },
        { label: 'Firewood or charcoal', key: 'firewoodOrCharcoal' },
        { label: 'Petty Trading', key: 'pettyTrading' },
        { label: 'Remittance', key: 'remittance' },
        { label: 'Bodaboda', key: 'bodaboda' },
        { label: 'Bee Keeping', key: 'beeKeeping' },
        { label: 'Sand Harvesting', key: 'sandHarvesting' },
        { label: 'Other', key: 'other.value' },
    ],
    foodConsumptionResponses: [
        { label: 'Beans', key: 'beans' },
        { label: 'Cooking Fat', key: 'cookingFats' },
        { label: 'Eggs', key: 'eggs' },
        { label: 'Fish', key: 'fish' },
        { label: 'Maize and Posho', key: 'maizeAndPosho' },
        { label: 'Milk', key: 'milk' },
        { label: 'Pulses', key: 'pulses' },
        { label: 'Rice', key: 'rice' },
        { label: 'Sorghum or millet', key: 'sorghumOrMillet'},
        { label: 'Rice', key: 'spices' },
        { label: 'Vegetables', key: 'vegetables'},
        { label: 'Wheat or barley', key: 'wheatOrBarley'},
        { label: 'White roots', key: 'whiteRoots'},
    ],
    cropContributionResponseItemsHeaders: [
        '',
        'Cash Income Rank', 
        'Cash Income Approx %age', 
        'Food Consumption Rank', 
        'Food Consumption Approx %age'
    ],

}